### ISSUE TITLE
Side Bar Menu With Games In A List

### ISSUE THREAD

**Issue by Joyananda** [shadesoflight/tumblr-template-sass#19] opened 2014-07-17 19:20 UTC
For something like this, would it be something i could add to myself whenever i need to, or would i have to put in a ticket for a new add to the list when i have to add a new game? Just curious.

**Comment by Joyananda** [comment] 2015-05-04 14:31
This is the same thing i posted about just now, sorry about that.

**Comment by shadesoflight** [comment] 2015-05-16 15:32
Duplicate of https://github.com/shadesoflight/tumblr-template-sass/issues/33

**Closed by shadesoflight** 2015-05-16 15:32 UTC
